
Vagrant.configure("2") do |config|
 
  config.vm.box = "ubuntu/xenial64"
  
  config.vm.hostname = "ubuntucitusdb"

  config.disksize.size = '25GB'
 
  config.vm.network "public_network"
 
  config.vm.provider "virtualbox" do |vb|
    
     vb.memory = "4024"
     vb.cpus = 4
   end
 
  config.vm.provision "shell", inline: <<-SHELL
    passwd -d -u ubuntu
    chage -d0 ubuntu
    sudo apt-get update


  sudo apt-get install git -y --allow-unauthenticated

  export pw='ubuntu'
  export usr='ubuntu'

  SHELL
   config.vm.provision "file", source: "Dockerfile", destination: "Dockerfile"
   config.vm.provision "file", source: "pg_hba.conf", destination: "pg_hba.conf"
   config.vm.provision "file", source: "users.csv", destination: "users.csv"
   config.vm.provision "file", source: "events.csv", destination: "events.csv"
   config.vm.provision "shell", path: "install_docker.sh"
   config.vm.provision "shell", path: "install_rdbms.sh"
end


